### ISSUE TITLE
misspelling in metric.py

### ISSUE THREAD

**Issue by steventan0110** [nyu-mll/crows-pairs#6]
Hi,

In the metric.py, from line 246 to 256, there seems to be a typo:
```
if direction == 'stereo':
    sent_more = data['sent1']
    sent_less = data['sent2']
    sent_more_score = score['sent1_score']
    sent_less_score = score['sent2_score']
else:
    sent_more = data['sent2']
    sent_less = data['sent1']
    sent_more_score = score['sent1_score']
    sent_less_score = score['sent2_score']
```
Here in the else block (anti-stereotype case), `sent_more_score` and `sent_less_score` should be flipped right? I believe this result in a mismatch between score and flag in saved csv file.

**Comment by claravania** [comment]
Thanks @steventan0110!

Sorry for the late response. Yes, the two variables should be flipped. I've fixed the bug and will close this issue, feel free to re-open if you have another question.

**Comment by sleepinyourhat** [comment]
For the record, we confirmed that this bug wasn't invoked in making the figures for the paper, so the paper is accurate as is.
